name: Release

on:
  push:
    tags:
      - 'v*'

# Required permissions for cargo-dist
permissions:
  contents: write
  id-token: write  # Required for GitHub Releases
  attestations: write
  checkout: write

jobs:
  release:
    uses: cargo-dist/gha-dist@v0.31.0
