name: Security

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release-please') == false # no need to redo on release-please PRs
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "RUSTSEC-2026-0098,RUSTSEC-2026-0099"
